### ISSUE TITLE
challenge edit API不能编辑题目URL

### ISSUE THREAD

**Issue by Windforce17** [vidar-team/hctf_backend#13]
URL一旦填错就不能改了..
https://github.com/vidar-team/hctf_backend/blob/4b227a65f22b2ab795abb3fd2cd1fd04d2cdd8cc/app/Http/Controllers/ChallengeController.php#L291-L305

**Comment by Last-Order** [comment]
added in e96b33b06f954d7e6079d712f093fa4095d787a8
